/* Auto-generated by Pymod on 2017-08-02 at 08:39:59 */

#define YES_IMPORT_ARRAY
#include <Python.h>
#include "pymodpkg/private/numpyarrayobject.h"
#include "nimcache/pmgennim_ext_wrap.h"


/*
 * Auto-generated from exported function `profile_sim`:
 *  /home/pahl/dev/python3/cellpainting/nim_ext/mod_profile_sim.nim(9, 0)
 */
static PyObject *
py_profile_sim(PyObject *class_, PyObject *args, PyObject *kwargs)
{
	const char *current_412;
	const char *reference_196;

	static char *kwlist[] = { "current", "reference", NULL };
	if (! PyArg_ParseTupleAndKeywords(args, kwargs, "ss", kwlist,
			&current_412, &reference_196)) {
		return NULL;
	}

	return exportpy_profile_sim(current_412, reference_196);
}


static PyMethodDef methods[] = {
	{ "profile_sim", (PyCFunction) py_profile_sim, METH_VARARGS | METH_KEYWORDS,
		"profile_sim(current: str, reference: str) -> (float)\n"
		"\n"
		"Parameters\n"
		"----------\n"
		"current : str -> string\n"
		"reference : str -> string\n"
		"\n"
		"Returns\n"
		"-------\n"
		"out : (float) <- (float)\n"
		"\n"
		"Calculate the similarity of two byte activity_profiles of the same length.\n"
		"Returns value between 0 .. 1\n"
	},
	{ NULL, NULL, 0, NULL },
};


PyMODINIT_FUNC
initnim_ext(void)
{
	PyObject *m = Py_InitModule("nim_ext", methods);
	if (m == NULL) {
		return;
	}
	import_array();
	NimMain();
}